version: "3.8"
services:
  #################################
#   Course: The course Service
  #################################
  course:
    build:
      context: ./
      dockerfile: course.Dockerfile
    image:  team01/course:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/lms_course
      PYTHONUNBUFFERED: 1
    ports:
      - "6900:6900"

